name: Build APK

on:
  push:
    branches:
      - main  # Triggers build when you push changes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build APK
      run: ./gradlew assembleRelease  # Use Gradle to build the APK
